language: erlang
branches:
        only:
                - master
notifications:
        email: mongoose-im@erlang-solutions.com
otp_release:
        - 19.3
        - 20.3
        - 21.0
install:
        - make
        - make test-compile
script:
        - make test
        - make dialyzer

after_success:
        - make coverage-report
